export {default as call} from './function/call'
export {apply} from './function/apply'
export {bind} from './function/bind'
export {throttle} from './function/throttle'
export {debounce} from './function/debounce'